"""User-visible Russian text and menu labels."""

START = "Здравствуйте! Это «Сократ» — помощник педагога для диагностических работ. Введите пароль."
LOGIN_REQUIRED = "Для работы с ботом нажмите /start и введите пароль."
PASSWORD_WRONG = "Пароль не подошёл. Попробуйте ещё раз."
LOGIN_LOCKED = "Слишком много попыток входа. Подождите несколько минут и попробуйте снова."
LOGIN_SUCCESS = "Вы вошли как {nick}."
ALREADY_LOGGED_IN = "Вы уже вошли как {nick}."
LOGGED_OUT = "Вы вышли. Чтобы войти снова, нажмите /start."
BOUNDARIES_INFO = (
    "«Сократ» показывает только выбранные планируемые результаты из каталога с источником, разделом "
    "и страницей. Это не проверка всего ФГОС. Коды результатов — внутренние идентификаторы, "
    "не номера пунктов. Время выполнения — расчётная оценка. Не вводите имена и другие данные детей."
)

CREATE_WORK = "📝 Создать работу"
ANALYZE_ERROR = "🔍 Анализ типичной ошибки"
BOUNDARIES = "ℹ️ Границы и источники"
ADMIN_PANEL = "⚙️ Админ-панель"
LOGOUT = "🚪 Выйти"

PROTECTED_MENU_LABELS = frozenset({CREATE_WORK, ANALYZE_ERROR, BOUNDARIES, ADMIN_PANEL, LOGOUT})

WORK_GRADE = "Выберите класс."
WORK_SUBJECT = "Выберите предмет."
WORK_NO_SUBJECTS = "Для этого класса пока нет предметов в нормативной базе. Выберите другой класс."
WORK_TOPIC = "Напишите тему работы. Например: «Внетабличное умножение и деление»."
WORK_TOPIC_NOT_FOUND = "Тема не найдена в программе {grade} класса по предмету. Близкие темы:"
WORK_KEEP_TOPIC = "Всё равно продолжить с моей темой"
WORK_LEVEL = "Выберите уровень заданий."
WORK_UUD = "Что диагностируем (УУД)?"
WORK_COUNT = "Выберите число заданий. Время рядом с кнопкой — расчётная оценка."
WORK_CONFIRM = "Проверьте параметры:\nКласс: {grade}\nПредмет: {subject}\nТема: {topic}\nУровень: {level}\nУУД: {uud}\nЗаданий: {count}"
WORK_BACK = "◀ Назад"
WORK_GENERATE = "✅ Сгенерировать"
WORK_EDIT = "✏️ Изменить"
WORK_CONTINUE = "Продолжить"
WORK_CANCELLED = "Создание работы отменено."
WORK_IN_PROGRESS = "Работа уже готовится. Дождитесь результата."
WORK_PREPARING = "⏳ Готовлю работу…"
WORK_FAILED = "Что-то пошло не так, попробуйте ещё раз."
WORK_RETRY = "Повторить"
WORK_RESULT = "Работа готова. План времени:\n{times}\nУУД: {groups}{warnings}"
WORK_WARNINGS = "\nПредупреждения:\n{items}"
WORK_FEEDBACK = "👍/👎 по заданиям"
WORK_REGENERATE = "🔁 Перегенерировать задание"
WORK_OBSERVE = "🧪 Разобрать ответ ученика"

ERROR_GRADE = "Выберите класс для анализа ошибки."
ERROR_SUBJECT = "Выберите предмет."
ERROR_TOPIC = "Напишите тему. Например: «Внетабличное умножение и деление»."
ERROR_TOPIC_SUGGESTIONS = (
    "Похожая тема в программе не найдена. Можно выбрать близкую тему или продолжить со своей."
)
ERROR_DESCRIPTION = "Опишите, какую ошибку делают дети и в каких заданиях. Без имён и фамилий."
ERROR_DESCRIPTION_SHORT = "Опишите наблюдаемую ошибку подробнее, не меньше 10 символов. Без имён и фамилий."
ERROR_PERSONAL_DATA = "Похоже, в тексте есть имя или фамилия ребёнка. Опишите ошибку без имён."
ERROR_WORKING = "⏳ Анализирую типичную ошибку…"
ERROR_DONE = "✅ Анализ готов."
ERROR_FAILED = "Не удалось выполнить анализ. Попробуйте ещё раз."
ERROR_DOCX = "📄 Скачать .docx"
ERROR_NO_RESULT = "Анализ больше недоступен. Запустите его снова."
ERROR_BACK = "◀ Назад"
ERROR_CONTINUE_TOPIC = "Продолжить с моей темой"
ERROR_CONTINUE = "Продолжить"
ERROR_EDIT = "Изменить описание"
ERROR_CANCELLED = "Анализ отменён."

ADMIN_FORBIDDEN = "Эта функция доступна только администратору."
ADMIN_TITLE = "⚙️ Админ-панель"
ADMIN_ADD = "➕ Добавить педагога"
ADMIN_TEACHERS = "👥 Педагоги"
ADMIN_KNOWLEDGE = "📚 Нормативная база"
ADMIN_USAGE = "💰 Расходы"
ADMIN_PAYMENT = "💳 Оплата"
ADMIN_SOON = "Скоро."
ADMIN_BACK = "◀ Назад"
ADMIN_NICK_PROMPT = "Введите ник педагога (от 2 до 64 символов). Не указывайте ФИО ученика."
ADMIN_NICK_INVALID = "Ник должен содержать от 2 до 64 символов."
ADMIN_NICK_EXISTS = "Такой ник уже существует. Введите другой."
ADMIN_ROLE_PROMPT = "Выберите роль педагога."
ADMIN_CREATED = (
    "Педагог «{nick}» создан. Пароль: {password} — передайте его лично, повторно он показан не будет."
)
ADMIN_PASSWORD_RESET = (
    "Новый пароль для «{nick}»: {password} — передайте его лично, повторно он показан не будет."
)
ADMIN_NO_TEACHERS = "Педагоги пока не добавлены."
ADMIN_TEACHER_DETAIL = "Педагог «{nick}»\nРоль: {role}\nСтатус: {status}"
ADMIN_ACTIVE = "активен"
ADMIN_INACTIVE = "отключён"
ADMIN_NOT_FOUND = "Педагог не найден."
ADMIN_RESET = "🔁 Сбросить пароль"
ADMIN_DISABLE = "🚫 Отключить"
ADMIN_ENABLE = "✅ Включить"
ADMIN_CHANGE_ROLE = "🎭 Сменить роль"
ADMIN_ROLE_CHANGED = "Роль педагога изменена."
ADMIN_STATUS_CHANGED = "Статус педагога изменён."
ADMIN_KNOWLEDGE_STATUS = "Статус"
ADMIN_KNOWLEDGE_UPDATE = "🔄 Обновить"
ADMIN_KNOWLEDGE_UPLOAD = "📎 Загрузить материал школы"
ADMIN_KNOWLEDGE_INFO = "Материалы школы используются как контекст и не являются нормативным источником."
ADMIN_KNOWLEDGE_REPORT = "Документы: {documents}\nФрагменты: {chunks}\nРезультаты: {outcomes}\nГотово: {ready}\nПроблемы: {problems}"
ADMIN_UPDATE_RUNNING = "⏳ Обновляю нормативную базу…"
ADMIN_UPDATE_DONE = (
    "Обновление завершено. Загружено: {downloaded}; без изменений: {unchanged}; ошибок: {failed}."
)
ADMIN_UPDATE_FAILED = "Не удалось обновить нормативную базу. Попробуйте позже."
ADMIN_UPLOAD_PROMPT = "Пришлите PDF или DOCX до 20 МБ без данных детей. Материал будет использоваться как контекст, не как нормативный источник."
ADMIN_UPLOAD_INVALID = "Нужен файл PDF или DOCX размером до 20 МБ."
ADMIN_UPLOAD_RUNNING = "⏳ Загружаю материал школы…"
ADMIN_UPLOAD_DONE = "Материал «{title}» загружен как ненормативный контекст."
ADMIN_UPLOAD_FAILED = "Не удалось загрузить материал. Попробуйте позже."
ADMIN_USAGE_REPORT = "За {days} дней: запросов {requests}, входных токенов {tokens_in}, выходных токенов {tokens_out}, стоимость ${cost:.4f}."
ADMIN_PREVIOUS = "◀"
ADMIN_NEXT = "▶"
ADMIN_READY_YES = "да"
ADMIN_READY_NO = "нет"
ADMIN_NO_PROBLEMS = "нет"
ADMIN_PROGRESS = "⏳ {description}"
